all:
  vars:
    ansible_user: namnv
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    etcd:
      hosts:
        etcd1:
          ansible_host: 10.10.0.10
