- name: Detect default route interface (e.g. ens4, eth0)
  command: ip route get 8.8.8.8
  register: route_info
  changed_when: false

- name: Extract real interface from route output
  set_fact:
    real_interface: "{{ route_info.stdout | regex_search('dev (\\S+)', '\\1') }}"

- name: Enable IP forwarding temporarily (runtime)
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable IP forwarding permanently
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward='
    line: 'net.ipv4.ip_forward=1'
    state: present
  notify: Reload sysctl

- name: Remove wrong MASQUERADE rules (not using {{ real_interface }})
  shell: |
    iptables-save | grep '10.8.0.0/24' | grep MASQUERADE | grep -v '{{ real_interface }}' \
    | sed -E 's/^-A/iptables -t nat -D/' | bash
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: true

- name: Check if correct MASQUERADE rule exists
  command: >
    iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o {{ real_interface }} -j MASQUERADE
  register: check_nat_rule
  failed_when: false
  changed_when: false

- name: Add MASQUERADE rule for correct interface if missing
  command: >
    iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o {{ real_interface }} -j MASQUERADE
  when: check_nat_rule.rc != 0

- block:
    - name: Install iptables-persistent (Debian)
      apt:
        name: iptables-persistent
        state: present

    - name: Save iptables rules (Debian)
      command: netfilter-persistent save
  when: ansible_os_family == "Debian"

- name: ✅ NAT setup done
  debug:
    msg: "✔️ NAT configured. Interface used: {{ real_interface }}"
