- name: Install PostgreSQL repo for EL-9
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install PostgreSQL {{ postgresql_version }} server
  yum:
    name: "postgresql{{ postgresql_version }}-server"
    state: present
    disable_gpg_check: yes

- name: Install PostgreSQL {{ postgresql_version }} client
  yum:
    name: "postgresql{{ postgresql_version }}"
    state: present
    disable_gpg_check: yes

