- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /etc/kubernetes/kube-vip

- name: Chạy kube-vip bằng podman và lưu manifest ra file YAML
  ansible.builtin.shell: >
    sudo podman run --rm --network host ghcr.io/kube-vip/kube-vip:v0.9.1
    manifest pod
    --interface eth1
    --address {{ vip_address }}
    --controlplane
    --services
    --arp
    --leaderElection
    | sudo tee /etc/kubernetes/manifests/kube-vip.yaml
  args:
    executable: /bin/bash
  become: true