apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  loadBalancerIP: 10.10.0.102
  ports:
    - port: 80
      targetPort: 80


#  kubectl expose deployment my-nginx --port=32380 --target-port=80 --type=LoadBalancer --load-balancer-ip=192.168.0.220