Vagrant.configure("2") do |config|
  nodes = [
    { name: "bgp-router",   ip: "10.10.0.200" },
    { name: "etcd-1",       ip: "10.10.0.10" },
    { name: "k8s-master-1", ip: "10.10.0.20" },
    { name: "k8s-master-2", ip: "10.10.0.21" }
  ];

  public_key = File.read(File.expand_path("~/.ssh/id_ed25519.pub"))

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = "debian/bookworm64"
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip], name: "vboxnet0"


      vm.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = 2048
        vb.cpus = 2
      end

      # Thêm user "namnv" + SSH key của bạn
      vm.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y sudo openssh-server
        useradd -m -s /bin/bash namnv
        echo 'namnv ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        mkdir -p /home/namnv/.ssh
        echo "#{public_key}" > /home/namnv/.ssh/authorized_keys
        chmod 600 /home/namnv/.ssh/authorized_keys
        chown -R namnv:namnv /home/namnv/.ssh
        systemctl enable ssh
        systemctl restart ssh
      SHELL
    end
  end
end
