---
- name: Cài đặt DevStack trên Ubuntu
  hosts: devstack
  become: true

  vars:
    devstack_user: stack
    host_ip: "127.0.0.1"
    admin_pass: admin

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Cài đặt gói phụ thuộc
      apt:
        name:
          - git
          - sudo
          - python3-pip
          - net-tools
          - curl
        state: present

    - name: Tạo user stack
      user:
        name: "{{ devstack_user }}"
        home: "/opt/{{ devstack_user }}"
        shell: /bin/bash
        state: present
        create_home: true

    - name: Tạo thư mục home cho stack
      file:
        path: "/opt/{{ devstack_user }}"
        state: directory
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        mode: '0755'

    - name: Cho phép stack sudo không cần mật khẩu
      copy:
        dest: "/etc/sudoers.d/{{ devstack_user }}"
        content: "{{ devstack_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    - name: Tạo thư mục devstack
      file:
        path: "/opt/{{ devstack_user }}/devstack"
        state: directory
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        mode: '0755'

    - name: Clone DevStack repo as stack user (workaround)
      become: true
      shell: sudo -u stack git clone https://opendev.org/openstack/devstack.git /opt/stack/devstack
      args:
        creates: /opt/stack/devstack/.git

    - name: Download Octavia Amphora image
      ansible.builtin.get_url:
        url: https://tarballs.opendev.org/openstack/octavia/test-images/test-only-amphora-x64-haproxy-ubuntu-focal.qcow2
        dest: /var/tmp/amphora-x64-haproxy.qcow2
        mode: '0644'
        force: no

    - name: Tạo file local.conf từ template
      template:
        src: files/local.conf.j2
        dest: "/opt/{{ devstack_user }}/devstack/local.conf"
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        mode: '0644'

    - name: Chạy ./stack.sh
      shell: sudo -u stack ./stack.sh
      args:
        chdir: "/opt/{{ devstack_user }}/devstack"

    # nếu trên giao diện dashboard/project/api_access/ chưa nhận ip mới thì logout ra vào lại
    - name: Cập nhật endpoint IP từ {{ OLD_IP }} → {{ NEW_IP }}
      vars:
        OLD_IP: "127.0.0.1"
        NEW_IP: "{{ ansible_host }}"
      shell: |
        source /opt/stack/devstack/openrc admin
        openstack endpoint list --interface public -f value -c ID -c URL | while read ID URL; do
          if echo "$URL" | grep -q "{{ OLD_IP }}"; then
            NEW_URL=$(echo "$URL" | sed "s|{{ OLD_IP }}|{{ NEW_IP }}|g")
            echo "openstack endpoint set --url '$NEW_URL' $ID"
            openstack endpoint set --url "$NEW_URL" "$ID"
          fi
        done
      args:
        executable: /bin/bash
      register: endpoint_update_result

    - name: In kết quả cập nhật endpoint
      debug:
        var: endpoint_update_result.stdout_lines


